package com.model.pojo;
// Generated Oct 2, 2019 11:39:09 PM by Hibernate Tools 4.3.1



/**
 * Daftar generated by hbm2java
 */
public class Daftar  implements java.io.Serializable {


     private Integer idDaftar;
     private int nimDaftar;
     private String namaDaftar;
     private String majorDaftar;
     private String kelasDaftar;
     private String hobby;
     private String reason;
     private String why;

    public Daftar() {
    }

    public Daftar(int nimDaftar, String namaDaftar, String majorDaftar, String kelasDaftar, String hobby, String reason, String why) {
       this.nimDaftar = nimDaftar;
       this.namaDaftar = namaDaftar;
       this.majorDaftar = majorDaftar;
       this.kelasDaftar = kelasDaftar;
       this.hobby = hobby;
       this.reason = reason;
       this.why = why;
    }
   
    public Integer getIdDaftar() {
        return this.idDaftar;
    }
    
    public void setIdDaftar(Integer idDaftar) {
        this.idDaftar = idDaftar;
    }
    public int getNimDaftar() {
        return this.nimDaftar;
    }
    
    public void setNimDaftar(int nimDaftar) {
        this.nimDaftar = nimDaftar;
    }
    public String getNamaDaftar() {
        return this.namaDaftar;
    }
    
    public void setNamaDaftar(String namaDaftar) {
        this.namaDaftar = namaDaftar;
    }
    public String getMajorDaftar() {
        return this.majorDaftar;
    }
    
    public void setMajorDaftar(String majorDaftar) {
        this.majorDaftar = majorDaftar;
    }
    public String getKelasDaftar() {
        return this.kelasDaftar;
    }
    
    public void setKelasDaftar(String kelasDaftar) {
        this.kelasDaftar = kelasDaftar;
    }
    public String getHobby() {
        return this.hobby;
    }
    
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getWhy() {
        return this.why;
    }
    
    public void setWhy(String why) {
        this.why = why;
    }




}


