package com.model.pojo;
// Generated Oct 2, 2019 11:39:09 PM by Hibernate Tools 4.3.1



/**
 * Keroh generated by hbm2java
 */
public class Keroh  implements java.io.Serializable {


     private Integer idKeroh;
     private String judulKeroh;
     private String deskripsiKeroh;

    public Keroh() {
    }

    public Keroh(String judulKeroh, String deskripsiKeroh) {
       this.judulKeroh = judulKeroh;
       this.deskripsiKeroh = deskripsiKeroh;
    }
   
    public Integer getIdKeroh() {
        return this.idKeroh;
    }
    
    public void setIdKeroh(Integer idKeroh) {
        this.idKeroh = idKeroh;
    }
    public String getJudulKeroh() {
        return this.judulKeroh;
    }
    
    public void setJudulKeroh(String judulKeroh) {
        this.judulKeroh = judulKeroh;
    }
    public String getDeskripsiKeroh() {
        return this.deskripsiKeroh;
    }
    
    public void setDeskripsiKeroh(String deskripsiKeroh) {
        this.deskripsiKeroh = deskripsiKeroh;
    }




}


