package com.model.pojo;
// Generated Oct 2, 2019 11:39:09 PM by Hibernate Tools 4.3.1



/**
 * Saran generated by hbm2java
 */
public class Saran  implements java.io.Serializable {


     private Integer idSaran;
     private int nim;
     private String nama;
     private String major;
     private String kelas;
     private String suggestion;

    public Saran() {
    }

    public Saran(int nim, String nama, String major, String kelas, String suggestion) {
       this.nim = nim;
       this.nama = nama;
       this.major = major;
       this.kelas = kelas;
       this.suggestion = suggestion;
    }
   
    public Integer getIdSaran() {
        return this.idSaran;
    }
    
    public void setIdSaran(Integer idSaran) {
        this.idSaran = idSaran;
    }
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public String getKelas() {
        return this.kelas;
    }
    
    public void setKelas(String kelas) {
        this.kelas = kelas;
    }
    public String getSuggestion() {
        return this.suggestion;
    }
    
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }




}


