package com.model.pojo;
// Generated Oct 2, 2019 11:39:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Integer idSchedule;
     private String namaAcara;
     private Date tanggal;
     private String namaDepartemen;
     private String description;

    public Schedule() {
    }

    public Schedule(String namaAcara, Date tanggal, String namaDepartemen, String description) {
       this.namaAcara = namaAcara;
       this.tanggal = tanggal;
       this.namaDepartemen = namaDepartemen;
       this.description = description;
    }
   
    public Integer getIdSchedule() {
        return this.idSchedule;
    }
    
    public void setIdSchedule(Integer idSchedule) {
        this.idSchedule = idSchedule;
    }
    public String getNamaAcara() {
        return this.namaAcara;
    }
    
    public void setNamaAcara(String namaAcara) {
        this.namaAcara = namaAcara;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getNamaDepartemen() {
        return this.namaDepartemen;
    }
    
    public void setNamaDepartemen(String namaDepartemen) {
        this.namaDepartemen = namaDepartemen;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


