package com.model.pojo;
// Generated Oct 2, 2019 11:39:09 PM by Hibernate Tools 4.3.1



/**
 * Sosma generated by hbm2java
 */
public class Sosma  implements java.io.Serializable {


     private Integer idSosma;
     private String judulSosma;
     private String deskripsiSosma;

    public Sosma() {
    }

    public Sosma(String judulSosma, String deskripsiSosma) {
       this.judulSosma = judulSosma;
       this.deskripsiSosma = deskripsiSosma;
    }
   
    public Integer getIdSosma() {
        return this.idSosma;
    }
    
    public void setIdSosma(Integer idSosma) {
        this.idSosma = idSosma;
    }
    public String getJudulSosma() {
        return this.judulSosma;
    }
    
    public void setJudulSosma(String judulSosma) {
        this.judulSosma = judulSosma;
    }
    public String getDeskripsiSosma() {
        return this.deskripsiSosma;
    }
    
    public void setDeskripsiSosma(String deskripsiSosma) {
        this.deskripsiSosma = deskripsiSosma;
    }




}


